### PR TITLE
Reduce library size and uses the most correct libraries

### PR DESCRIPTION
**Pull request by ppamorim**
A lot of changes, with a new way to perform animations with support library and removed the unnecessary .idea folder.
Unfortunately I had to temporarily increase the API. However, the library size and the amount of biblotecas decreased. We don\`t need NineOlds right now because it`s deprecated.
What do you think to add an CI?

### CODE REVIEW

**Comment by android-cjj** [comment]
Because want to compatible to api 8, so use
JakeWharton/NineOldAndroids

**Comment by ppamorim** [comment]
@android-cjj API 8 is very old. We don`t need to support this API right now. Maybe in the future...

**Comment by ppamorim** [comment]
@android-cjj NineOlds was deprecated. We have a another support library to do that.

**Comment by android-cjj** [comment]
@ppamorim  nice to meet you, maybe we can become the friend, also, my English is not very good

**Comment by ppamorim** [comment]
@android-cjj Anyone that wants to use this library with API 8. Please, clone the project and do it by yourself. We don`t have any tecnical reason to support API 8. We can support API 10, that`s fine!

**Comment by ppamorim** [comment]
@android-cjj. No problems. You can add me at Hangouts and drink a coffe as you like. I use my hangout account with my email from Gmail, then, you can add me.

**Pull request merged**
